name: release-tag

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Extract and Store Trimmed Repository Name
        run: |
          REPO_CHART_NAME="${{ github.repository }}"
          REPO_APP_NAME=$(echo "$REPO_CHART_NAME" | sed 's/-chart$//')  # Remove "-chart" suffix if present
          
          # Check if the trimmed repo exists
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO_APP_NAME")

          if [[ "$HTTP_STATUS" -eq 200 ]]; then
            echo "Using trimmed repository name: $REPO_APP_NAME"
            echo "REPO_APP_NAME=$REPO_APP_NAME" >> $GITHUB_ENV
          else
            echo "Trimmed repository not found. Falling back to original repository name."
            echo "REPO_APP_NAME=$REPO_CHART_NAME" >> $GITHUB_ENV
          fi

      - name: Use the Stored Variable
        run: |
          echo "Trimmed Repository Name: ${{ env.REPO_APP_NAME }}"

      - name: Authenticate with GitHub App
        id: authenticate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v5

      - uses: oras-project/setup-oras@v1
        with:
          version: 1.3.0

      - name: Login to GitHub Container Registry (GHCR) using GitHub App token
        run: |
          echo "${{ steps.authenticate.outputs.token }}" | oras login ghcr.io \
            -u x-access-token --password-stdin

      - run: oras version

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 1.4.2

      - name: Build OPA Bundle
        run: opa build -b policies/

      - name: Push OPA Bundle to Container Registry with ORAS
        run: |
          oras push ghcr.io/krateoplatformops/${{ env.REPO_APP_NAME }}:${{ github.ref_name }} \
            --config config.json:application/vnd.oci.image.config.v1+json \
            bundle.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip